### ISSUE TITLE
Conceptual diagram artist

### ISSUE THREAD

**Issue by slarge** [sgaichas/SOEpaper#3]
Do we need to credit the artist that created the conceptual diagrams? Or do we own copyright? Not sure how all that works

**Comment by slarge** [comment]
Further, it might be a good idea to provide more info in the caption, perhaps: 

> Figure 1. Overview of ecosystem relationships for the Mid-Atlantic Ecosystem. Human activities link to high level strategic management objectives (MAFMC FMP). Components are represented by indicators in this report, and key paths connecting components and objectives are highlighted.

 Finally, will Social Scientists want the modified figure without the 💰? Or, are we going to go with SOE figures as they were presented.

**Comment by sgaichas** [comment]
Mike Fogarty confirmed that we own the copyright. I added Traynor Design to the acknowledgements section in https://github.com/sgaichas/SOEpaper/commit/5fc3cd0f36fab114f29bd173cd2413deb574f009
Tracking additional SSB updates in progress...
