### ISSUE TITLE
Add numbers to priority

### ISSUE THREAD

**Issue by slarge** [sgaichas/SOEpaper#4]
In the Methods and Results sections, the multiple priorities are presented. I wonder if it will be more clear to add a number, e.g., 

Priority 1: Clear communication of relevance to management 
Priority 2: Synthesis across indicators
Priority 3: Efficient production for multiple management jurisdictions

The results section of the .pdf version (esp. pp 5-7) are a bit busy with the bold text, bold sections, and bold subsections. Perhaps adding a number will help differentiate and order between the sections/subsections. 

edit: I'm don't think subsection numbers (e.g., 1.1, 1.2, 1.3) would be necessary, though.

**Comment by slarge** [comment]
Alternatively, I wonder if PLoS direct quotes actually end up looking like this (with a vertical bar)?

>The purpose of this report is to provide **ecosystem-scale information for fishery managers** to consider along with existing species-scale analyses.  An overview of ecosystem relationships as represented by **a conceptual model helps place more detailed species-level management in context** by highlighting relationships between focal species groups organized by Mid Atlantic Fishery Management Council (MAFMC) Fishery Management Plan (FMP), managed human activities, environmental drivers, habitats, and key ecological links (Fig \@ref(fig:conceptual)). Here, human activities link to high level strategic management objectives. Many components of the conceptual model are represented by indicators in this report, and key paths connecting components and objectives are highlighted.

**Comment by sgaichas** [comment]
I agree, the quotes in the pdf are hard to differentiate and the bold is confusing. Maybe we could ask them to put the direct quotes in a box or something? Or use a different font? I wasn't sure how much to break their template.... The vertical bar would help if that is how they do the html version.  I briefly looked for PLoS papers with block quotes but couldn't find any.

My only concern with numbering the priorities is that I think of them all as important (we couldn't really sacrifice streamlined production, for example). But the ranking implied by the numbers is probably ok. I'll see what I can do.

**Comment by sgaichas** [comment]
I've put the quotes in italic text for now to go through internal review. It would be great if the journal let us do all the quoted sections as boxes along with their associated figures. I'll ask for that in the cover letter when we submit.
